x=int(input("Enter the value of x:"))
y=int(input("Enter the value of y:"))
print("value of x before swapping =",x)
print("value of y before swapping =",y)
x=x^y
y=x^y
x=x^y
print("value of x before swapping =",x)
print("value of y before swapping =",y)
